# Generated by Django 4.2.4 on 2023-08-20 19:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('bookmark', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collectoins', to=settings.AUTH_USER_MODEL, verbose_name='Коллекция пользователя'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='collections',
            field=models.ManyToManyField(blank=True, to='bookmark.collection', verbose_name='Коллекции'),
        ),
        migrations.AddField(
            model_name='bookmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookmarks', to=settings.AUTH_USER_MODEL, verbose_name='Закладка пользователя'),
        ),
    ]
