# Generated by Django 4.2.4 on 2023-08-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bookmark',
            name='image_preview',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на изображение'),
        ),
    ]
