# Generated by Django 4.2.4 on 2023-08-21 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookmark', '0003_alter_bookmark_image_preview'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookmark',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='bookmark',
            name='updated_at',
        ),
        migrations.AlterField(
            model_name='bookmark',
            name='collections',
            field=models.ManyToManyField(blank=True, null=True, to='bookmark.collection', verbose_name='Коллекции'),
        ),
    ]
